/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutRuleConfigsRouteImport } from './routes/_layout.rule-configs'
import { Route as LayoutConfigRouteImport } from './routes/_layout.config'
import { Route as LayoutRequestsRequestIdRouteImport } from './routes/_layout.requests.$requestId'
import { Route as LayoutFoldersFolderIdRouteImport } from './routes/_layout.folders.$folderId'
import { Route as LayoutWorkspacesWorkspaceIdIndexRouteImport } from './routes/_layout.workspaces.$workspaceId.index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRuleConfigsRoute = LayoutRuleConfigsRouteImport.update({
  id: '/rule-configs',
  path: '/rule-configs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfigRoute = LayoutConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRequestsRequestIdRoute = LayoutRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFoldersFolderIdRoute = LayoutFoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkspacesWorkspaceIdIndexRoute =
  LayoutWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/config': typeof LayoutConfigRoute
  '/rule-configs': typeof LayoutRuleConfigsRoute
  '/folders/$folderId': typeof LayoutFoldersFolderIdRoute
  '/requests/$requestId': typeof LayoutRequestsRequestIdRoute
  '/workspaces/$workspaceId/': typeof LayoutWorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/config': typeof LayoutConfigRoute
  '/rule-configs': typeof LayoutRuleConfigsRoute
  '/': typeof LayoutIndexRoute
  '/folders/$folderId': typeof LayoutFoldersFolderIdRoute
  '/requests/$requestId': typeof LayoutRequestsRequestIdRoute
  '/workspaces/$workspaceId': typeof LayoutWorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/config': typeof LayoutConfigRoute
  '/_layout/rule-configs': typeof LayoutRuleConfigsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/folders/$folderId': typeof LayoutFoldersFolderIdRoute
  '/_layout/requests/$requestId': typeof LayoutRequestsRequestIdRoute
  '/_layout/workspaces/$workspaceId/': typeof LayoutWorkspacesWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/config'
    | '/rule-configs'
    | '/folders/$folderId'
    | '/requests/$requestId'
    | '/workspaces/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/config'
    | '/rule-configs'
    | '/'
    | '/folders/$folderId'
    | '/requests/$requestId'
    | '/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/config'
    | '/_layout/rule-configs'
    | '/_layout/'
    | '/_layout/folders/$folderId'
    | '/_layout/requests/$requestId'
    | '/_layout/workspaces/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rule-configs': {
      id: '/_layout/rule-configs'
      path: '/rule-configs'
      fullPath: '/rule-configs'
      preLoaderRoute: typeof LayoutRuleConfigsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/config': {
      id: '/_layout/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof LayoutConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/requests/$requestId': {
      id: '/_layout/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof LayoutRequestsRequestIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/folders/$folderId': {
      id: '/_layout/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof LayoutFoldersFolderIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workspaces/$workspaceId/': {
      id: '/_layout/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof LayoutWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutConfigRoute: typeof LayoutConfigRoute
  LayoutRuleConfigsRoute: typeof LayoutRuleConfigsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFoldersFolderIdRoute: typeof LayoutFoldersFolderIdRoute
  LayoutRequestsRequestIdRoute: typeof LayoutRequestsRequestIdRoute
  LayoutWorkspacesWorkspaceIdIndexRoute: typeof LayoutWorkspacesWorkspaceIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutConfigRoute: LayoutConfigRoute,
  LayoutRuleConfigsRoute: LayoutRuleConfigsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFoldersFolderIdRoute: LayoutFoldersFolderIdRoute,
  LayoutRequestsRequestIdRoute: LayoutRequestsRequestIdRoute,
  LayoutWorkspacesWorkspaceIdIndexRoute: LayoutWorkspacesWorkspaceIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
